output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true
max-line-length: 123

dodgy:
    run: true

pep8:
    full: true

pylint:
    disable:
        - no-self-use
        - unused-argument
        - redefined-outer-name
        - too-few-public-methods
