output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true
max-line-length: 123

pep8:
    full: true

pylint:
    disable:
        - redefined-outer-name

dodgy:
    run: true
