output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

pep8:
    full: true

pylint:
    disable:
        - redefined-outer-name

dodgy:
    run: true
